---
items:
- src:
    dir: ./internal/domain
    interface: FileSystem
  dest:
    package: test
    file: internal/test/filesystem.go
- src:
    dir: ./internal/domain
    interface: Printer
  dest:
    package: test
    file: internal/test/printer.go
- src:
    dir: ./internal/domain
    interface: ConfigReader
  dest:
    package: test
    file: internal/test/config_reader.go
- src:
    dir: ./internal/domain
    interface: Downloader
  dest:
    package: test
    file: internal/test/downloader.go
- src:
    dir: ./internal/domain
    interface: GetArchiver
  dest:
    package: test
    file: internal/test/get_archiver.go
- src:
    dir: ./internal/domain
    interface: GetGzipReader
  dest:
    package: test
    file: internal/test/get_gzip_reader.go
- src:
    dir: ./internal/domain
    interface: Logic
  dest:
    package: test
    file: internal/test/logic.go
- src:
    package: os
    interface: FileInfo
  dest:
    package: test
    file: internal/test/file_info.go
- src:
    package: io
    interface: Writer
  dest:
    package: usecase
    file: internal/usecase/writer.go
- src:
    package: io
    interface: WriteCloser
  dest:
    package: test
    file: internal/test/write_closer.go
